#spring properties

db:
  url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shop_db}
  username: ${DB_USER:postgres}
  password: ${DB_PASSWORD:secret}
  driver: org.postgresql.Driver